Resources:
  MeetingTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: ${self:custom.deletionPolicy.${sls:stage}}
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}-meeting
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi_1
          KeySchema:
          - AttributeName: sk
            KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
            - wsConnectionID
            - meetingID
            - email
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  DDBMeetingStreamDLQ:
    Type: AWS::SQS::Queue

Outputs:
  DDBTableMeeting:
    Value: !Ref MeetingTable
  DDBTableMeetingArn:
    Value: !GetAtt MeetingTable.Arn
  DDBTableMeetingStreamArn:
    Value: !GetAtt MeetingTable.StreamArn
  DDBTableMeetingStreamDLQ:
    Value: !Ref DDBMeetingStreamDLQ
  DDBTableMeetingStreamDLQArn:
    Value: !GetAtt DDBMeetingStreamDLQ.Arn